trigger: 
  branches:
    include:
      - main

variables:
  - group: 'vercel-migration-secrets'  # your variable group with DATABASE_URL
  - name: workingdir
    value: '$(System.DefaultWorkingDirectory)/infra'
  - name: appdir
    value: '$(System.DefaultWorkingDirectory)/app'  # your Next.js app folder

stages:
- stage: Terraform
  displayName: "Terraform Infrastructure"
  jobs:
  - job: DeployInfra
    displayName: "Deploy Terraform Infra"
    steps:
    - checkout: self 
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.5.7' 
    - task: AzureCLI@2
      displayName: 'Terraform Init'
      inputs:
        azureSubscription: $(SERVICE_CONNECTION)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          terraform init -backend-config="storage_account_name=$(TF_STATE_STORAGE_ACCOUNT)" \
                         -backend-config="container_name=$(TF_STATE_CONTAINER)" \
                         -backend-config="key=$(TF_STATE_KEY)" \
                         -backend-config="resource_group_name=$(TF_STATE_RG)" \
                         -input=false
        workingDirectory: '$(workingdir)' 
    - task: AzureCLI@2
      displayName: 'Terraform Plan'
      inputs:
        azureSubscription: $(SERVICE_CONNECTION)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          terraform plan -var "database_url=$(DATABASE_URL)" -out=tfplan -input=false
        workingDirectory: '$(workingdir)'

    - task: AzureCLI@2
      displayName: 'Terraform Apply'
      inputs:
        azureSubscription: $(SERVICE_CONNECTION)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          terraform apply tfplan -input=false
        workingDirectory: '$(workingdir)'

- stage: AppDeploy
  displayName: "Deploy Next.js App"
  dependsOn: Terraform
  jobs:
  - job: DeployApp
    displayName: "Deploy App to Azure"
    steps:
    - checkout: self

    # Build Next.js app
    - script: |
        cd $(appdir)
        npm install
        npm run build
      displayName: 'Build Next.js App'

    # Deploy to Azure Web App
    - task: AzureWebApp@1
      inputs:
        azureSubscription: $(SERVICE_CONNECTION)
        appName: 'vercel-migration-app'
        package: '$(appdir)/.next'
        appSettings: '-DATABASE_URL=$(DATABASE_URL)'
